### ISSUE TITLE
Exceptions in backdoors are caught by calabash server, preventing crash reports

### ISSUE THREAD

**Issue by majasb** [calabash/calabash-ios-server#330]
After we upgraded recently, when code called from a backdoor throws an exception, the application no longer crashes, and so we no longer get a crash report. Instead we get the log lines produced by this pull request:
https://github.com/calabash/calabash-ios-server/pull/156

This prevents us from finding the error in our code. We need the crash report for that. 

It looks like #156 is a workaround for some specific problem. Could you change the implementation to only apply to that problem?

**Comment by jmoody** [comment]
>  Could you change the implementation to only apply to that problem?

That is a very good question.

The problem is that some users have been using Runtime Attributes in their xibs to set the accessibilityIdentifier for a view.  They have not been respecting the fact that accessibilityIdentifiers need to be NSString - they are using NSNumber.

Starting in Xcode 7, users can directly set the accessibilityIdentifier in an xib so this problem should not happen any more.

Can you show us the logs?  Maybe we can help diagnosis the problem?

I am not opposed to removing this try/catch block, but I will need to discuss with the team.

**Comment by jmoody** [comment]
ATTN @krukow @sapieneptus

**Comment by jmoody** [comment]
@majasb I think we will remove this once Xcode 8 has been released.  At the moment, there are too many people messing up the Runtime Attributes in their xibs.

**Comment by jmoody** [comment]
Fix will be available in 0.21.6.
